openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
tags:
  - name: Auth
    description: authentication
  - name: API

components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      


paths:
  /login:
    post:
      tags: 
        - Auth
      summary: Login process.
      requestBody:
        description: login requierements
        content:
          application/json:
            schema:
              properties: 
                username:
                  type: string
                  example: femresirvan 
                password:
                  type: string
                  description: password
                  example: 123456
        required: true
      responses:
        '200':
          description: JSON object 
          content:
            application/json:
              schema: 
                properties:
                  token:  
                    type: string 
  /signup:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        description: signup requierements
        content:
          application/json:
            schema:
              properties: 
                username:
                  type: string 
                password:
                  type: string
                  description: password
      responses:
        '200':    # TO DO
          description: JSON object 
          content:
            application/json:
              schema: 
                properties:
                  token:  
                    type: string                        
  /user/profile:
    get:
      tags:
        - API
      summary: get current user info
      security:
        - Authorization: []
      responses:
        '200':
          description: JSON object 
          content:
            application/json:
              schema: 
                properties:
                  message:  
                    type: string
                  user:
                    type: object
                    properties:
                      _id:
                        type: string
                      username:
                        type: string
  /user/reset_password:
    put:
      tags:
        - API
      summary: reset password
      security:
        - Authorization: []
      responses:
        '200':
          description: JSON object 
          content:
            application/json:
              schema: 
                properties:
                  message:  
                    type: string
  /user/delete_user:
    delete:
      tags:
        - API
      summary: Delete user
      security:
        - Authorization: []
      responses:
        '200':
          description: JSON object 
          content:
            application/json:
              schema: 
                properties:
                  message:  
                    type: string


